[[redirects]]
  from = "/random-quote-generator/*"
  to = "https://magical-queijadas-8ee93c.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/markdown-previewer/*"
  to = "https://euphonious-mandazi-1b5b65.netlify.app/"
  status = 200
  force = true


[[redirects]]
  from = "/drum-machine/*"
  to = "https://whimsical-kitsune-ec8c9e.netlify.app/"
  status = 200
  force = true