[[redirects]]
  from = "https://magical-queijadas-8ee93c.netlify.app/:splat"
  to = "/random-quote-generator/*"
  status = 200
  force = true

[[redirects]]
  from = "https://euphonious-mandazi-1b5b65.netlify.app/:splat"
  to = "/markdown-previewer/*"
  status = 200
  force = true


[[redirects]]
  from = "https://whimsical-kitsune-ec8c9e.netlify.app/:splat"
  to = "/drum-machine/*"
  status = 200
  force = true